package io.salat.sparser

enum class ParsingErrorType {
    NO_TOKENS_PRESENT,
    COMMAND_DOES_NOT_EXIST,
    ARGUMENT_WRONG_NAME_FORMAT,
    ARGUMENT_DOES_NOT_EXIST,

    REQUIRED_ARGUMENT_DOES_NOT_HAVE_DEFAULT_VALUE,

    ENUM_VALUE_DOES_NOT_EXIST

}